name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.1"

      - name: Install dependencies (libpcap-dev)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build ./...

      # Uncomment for tests if desired:
      # - name: Test
      #   run: go test ./... -v
